name: Continuous Delivery

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Unshallow repo
        run: git fetch --prune --unshallow
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: Run goreleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: v1.17.2s
          args: release --clean
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  # homebrew:
  #   runs-on: self-hosted
  #   steps:
  #     - name: Bump Homebrew formula
  #       uses: dawidd6/action-homebrew-bump-formula@v3
  #       with:
  #         token: ${{secrets.PAT}}
  #         formula: lazygit
